language: node_js
node_js:
  - 20.10.0
before_install:
  - npm install -g yarn
git:
  depth: 3
script: yarn test-ci && yarn lint --no-fix --max-warnings 0
cache:
  yarn: true
  directories:
    # for Cypress binary
    - ~/.cache
